version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app-network
  php:
    build:
      context: ./php
    container_name: php_container
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge